const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getConfig: () => ipcRenderer.invoke('get-config'),
  saveBuckets: (buckets) => ipcRenderer.invoke('save-buckets', buckets),
  setLeague: (league) => ipcRenderer.invoke('set-league', league),
  setDefaults: (items, enabled) => ipcRenderer.invoke('set-defaults', items, enabled),
  setOverrides: (overrides) => ipcRenderer.invoke('set-overrides', overrides),
  setTutorialDone: () => ipcRenderer.invoke('set-tutorial-done'),
  getFeedStatus: () => ipcRenderer.invoke('get-feed-status'),
  onFeedChanged: (cb) => ipcRenderer.on('feed-changed', cb),
  getUpdateState: () => ipcRenderer.invoke('get-update-state'),
  onUpdateState: (cb) => ipcRenderer.on('update-state', (_e, s) => cb(s)),
  installUpdate: () => ipcRenderer.send('install-update'),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  setUiScale: (v) => ipcRenderer.invoke('set-ui-scale', v),
  setBgOpacity: (v) => ipcRenderer.invoke('set-bg-opacity', v),
  setExcludeExaltedArb: (on) => ipcRenderer.invoke('set-exclude-exalted-arb', on),
  setCurrencyIcons: (on) => ipcRenderer.invoke('set-currency-icons', on),
  checkUpdates: () => ipcRenderer.send('check-updates-now'),
  getLiveRates: () => ipcRenderer.invoke('get-live-rates'),
  onLiveRates: (cb) => ipcRenderer.on('live-rates', (_e, r) => cb(r)),
  setHotkey: (accelerator) => ipcRenderer.invoke('set-hotkey', accelerator),
  setItemHotkeys: (binds) => ipcRenderer.invoke('set-item-hotkeys', binds),
  onTempMode: (cb) => ipcRenderer.on('overlay-temp-mode', (_e, v) => cb(v)),
  openExternal: (url) => ipcRenderer.send('open-external', url),
  submitFeedback: (payload) => ipcRenderer.invoke('submit-feedback', payload),
  fetchPrices: (force) => ipcRenderer.invoke('fetch-prices', force),
  fetchCatalog: () => ipcRenderer.invoke('fetch-catalog'),
  listLeagues: () => ipcRenderer.invoke('list-leagues'),
  hide: (toGame) => ipcRenderer.send('hide-overlay', !!toGame),
  focusOverlay: () => ipcRenderer.send('focus-overlay'),
  quit: () => ipcRenderer.send('quit-app'),
  onShown: (cb) => ipcRenderer.on('overlay-shown', cb),
  // item price-check (trade2)
  trade2Search: (league, query) => ipcRenderer.invoke('trade2-search', { league, query }),
  trade2Fetch: (ids, queryId) => ipcRenderer.invoke('trade2-fetch', { ids, queryId }),
  trade2SearchFetch: (league, query, limit) => ipcRenderer.invoke('trade2-search-fetch', { league, query, limit }),
  trade2Leagues: () => ipcRenderer.invoke('trade2-leagues'),
  trade2AuthCheck: (league, force) => ipcRenderer.invoke('trade2-auth-check', { league, force }),
  poeLogin: () => ipcRenderer.invoke('poe-login'),
  setItemHistory: (history) => ipcRenderer.invoke('set-item-history', history),
  setDesecHistory: (history) => ipcRenderer.invoke('set-desec-history', history),
  setItemRanges: (ranges) => ipcRenderer.invoke('set-item-ranges', ranges),
  setGarbagePool: (ids) => ipcRenderer.invoke('set-garbage-pool', ids),
  setItemSearchOpts: (o) => ipcRenderer.invoke('set-item-search-opts', o),
  itemPeekShow: (payload) => ipcRenderer.send('item-peek-show', payload),
  itemPeekHide: () => ipcRenderer.send('item-peek-hide'),
  readClipboard: () => ipcRenderer.invoke('read-clipboard'),
  onItemCopied: (cb) => ipcRenderer.on('item-copied', (_e, text) => cb(text)),
  onItemCopyFailed: (cb) => ipcRenderer.on('item-copy-failed', () => cb()),
  onTrade2Wait: (cb) => ipcRenderer.on('trade2-wait', (_e, info) => cb(info)),
  writeClipboard: (text) => ipcRenderer.invoke('write-clipboard', text),
  // Item hover tooltip
  getItemHoverConfig: () => ipcRenderer.invoke('get-item-hover-config'),
  setItemHoverConfig: (config) => ipcRenderer.invoke('set-item-hover-config', config)
});
